version: "3"
services:
  launcher:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    volumes:
      - ./:/launcher
    environment:
      FLASK_ENV: development


